---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy backend tar.gz file and unzipping it"
  become: yes
  ansible.builtin.unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu
    
- name: install
  become: true
  shell: npm install
  args:
    chdir: /home/ubuntu/backend    

- name: Build
  become: true
  shell: npm run build
  args:
    chdir: /home/ubuntu/backend   
    

- name: "start pm2"
  become: yes
  shell: pm2 start --name "backend" npm -- start
  args:
    chdir: /home/ubuntu/backend  