apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
  replicas: 2
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: DOCKER_IMAGE_NAME
        env:
        - name: DATABASE_USER
          value: DATABASE_USER_VALUE
        - name: DATABASE_URL
          value: DATABASE_URL_VALUE
        - name: DATABASE_PASSWORD
          value: DATABASE_PASSWORD_VALUE
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
        ports:
        - containerPort: 8080