apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
  replicas: 2
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/employeeservice:latest
        ports:
        - containerPort: 8080