apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
  replicas: 2
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: DOCKER_IMAGE_NAME
        ports:
        - containerPort: 8080