
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Capstone21
    url: jdbc:mysql://capstone.caejyuh3eggl.eu-west-1.rds.amazonaws.com:3306/capstone
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
