
logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
